import type { Chat } from "../types/chat.types";

/**
 * UzCode AI — Sample seed conversation.
 * Static demo data (same spirit as Sprint 5/6's mock data) exercising
 * every message type and Markdown feature this sprint needs to
 * render: user/assistant/system, a thinking block, a tool-call block,
 * code fences (multi-language), tables, lists, inline code. None of
 * this was generated by a model — it's fixture content.
 */
export const sampleChats: Chat[] = [
  {
    id: "chat-1",
    title: "Refactor auth service",
    pinned: true,
    modelId: "claude",
    updatedAt: new Date().toISOString(),
    messages: [
      {
        id: "msg-1",
        role: "system",
        status: "complete",
        createdAt: new Date().toISOString(),
        content: "You are UzCode AI, a senior engineering assistant embedded in the workspace.",
      },
      {
        id: "msg-2",
        role: "user",
        status: "complete",
        createdAt: new Date().toISOString(),
        content: "Can you review this function and suggest improvements?\n\n```ts\nfunction add(a,b) { return a+b }\n```",
      },
      {
        id: "msg-3",
        role: "assistant",
        status: "thinking",
        createdAt: new Date().toISOString(),
        content: "Analyzing the function signature and formatting conventions…",
      },
      {
        id: "msg-4",
        role: "assistant",
        status: "tool-call",
        createdAt: new Date().toISOString(),
        content: "Reading `lib/utils.ts` for existing conventions.",
        toolCall: { id: "tool-1", name: "read_file", status: "done" },
      },
      {
        id: "msg-5",
        role: "assistant",
        status: "complete",
        createdAt: new Date().toISOString(),
        content: [
          "Here's a cleaned-up version with explicit types:",
          "",
          "```ts",
          "function add(a: number, b: number): number {",
          "  return a + b;",
          "}",
          "```",
          "",
          "**Changes:**",
          "",
          "- Added explicit parameter and return types",
          "- Added spacing around operators per your Prettier config",
          "",
          "| Before | After |",
          "|---|---|",
          "| `add(a,b)` | `add(a: number, b: number)` |",
          "| No return type | `: number` |",
          "",
          "Also consider using `inline code` for short references like `Array.prototype.reduce`.",
        ].join("\n"),
      },
    ],
  },
  {
    id: "chat-2",
    title: "Explain the deploy pipeline",
    pinned: false,
    modelId: "gpt",
    updatedAt: new Date(Date.now() - 86_400_000).toISOString(),
    messages: [
      {
        id: "msg-6",
        role: "user",
        status: "complete",
        createdAt: new Date(Date.now() - 86_400_000).toISOString(),
        content: "What does our deploy pipeline look like?",
      },
    ],
  },
];
